// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0zofCJkJWaXzMW9JLQcob3HNDDIzrurU',
    appId: '1:210178686287:web:cb3c0d0f73d401716c593a',
    messagingSenderId: '210178686287',
    projectId: 'krushi-43e83',
    authDomain: 'krushi-43e83.firebaseapp.com',
    storageBucket: 'krushi-43e83.firebasestorage.app',
    measurementId: 'G-H5W0F8L1VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlLnW68RsPknlxvTOZs9rqD0YKWMmu4sg',
    appId: '1:210178686287:android:37bca487149efa136c593a',
    messagingSenderId: '210178686287',
    projectId: 'krushi-43e83',
    storageBucket: 'krushi-43e83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdNBlcHMegFiKD_N03pQCpXSI2jQtaAE8',
    appId: '1:210178686287:ios:559a53dbdecf1b9c6c593a',
    messagingSenderId: '210178686287',
    projectId: 'krushi-43e83',
    storageBucket: 'krushi-43e83.firebasestorage.app',
    iosBundleId: 'com.example.krushiAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdNBlcHMegFiKD_N03pQCpXSI2jQtaAE8',
    appId: '1:210178686287:ios:559a53dbdecf1b9c6c593a',
    messagingSenderId: '210178686287',
    projectId: 'krushi-43e83',
    storageBucket: 'krushi-43e83.firebasestorage.app',
    iosBundleId: 'com.example.krushiAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0zofCJkJWaXzMW9JLQcob3HNDDIzrurU',
    appId: '1:210178686287:web:e78b64bc87b6a0f96c593a',
    messagingSenderId: '210178686287',
    projectId: 'krushi-43e83',
    authDomain: 'krushi-43e83.firebaseapp.com',
    storageBucket: 'krushi-43e83.firebasestorage.app',
    measurementId: 'G-EX5Q95KQCK',
  );
}
